/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spark_chat;

/**
 *
 * @author aiaka
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        SignUp = new javax.swing.JButton();
        SignIn = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 29, 32));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setForeground(java.awt.Color.gray);
        setPreferredSize(new java.awt.Dimension(400, 655));
        setResizable(false);
        getContentPane().setLayout(null);

        UsernameInput.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        UsernameInput.setForeground(new java.awt.Color(51, 51, 51));
        UsernameInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsernameInput.setToolTipText("");
        UsernameInput.setAutoscrolls(false);
        UsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameInputActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameInput);
        UsernameInput.setBounds(150, 360, 200, 30);

        PasswordInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PasswordInput.setToolTipText("");
        getContentPane().add(PasswordInput);
        PasswordInput.setBounds(150, 400, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spark_chat/flash-icon-21.png"))); // NOI18N
        jLabel1.setAlignmentX(0.5F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 260, 270);

        SignUp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SignUp.setText("Sign up");
        SignUp.setToolTipText("");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp);
        SignUp.setBounds(90, 450, 100, 40);

        SignIn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SignIn.setText("Sign in");
        SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInActionPerformed(evt);
            }
        });
        getContentPane().add(SignIn);
        SignIn.setBounds(200, 450, 100, 40);

        Username.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("User name");
        Username.setAutoscrolls(true);
        getContentPane().add(Username);
        Username.setBounds(40, 360, 120, 30);

        Password.setFont(new java.awt.Font("Helvetica LT Std Light", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        getContentPane().add(Password);
        Password.setBounds(50, 400, 110, 30);

        bgImage.setToolTipText("");
        bgImage.setAlignmentX(0.5F);
        getContentPane().add(bgImage);
        bgImage.setBounds(-10, -110, 410, 770);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\NSU Studies\\CSE-215\\Programs\\Spark_chat\\src\\spark_chat\\bg pic.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameInputActionPerformed

    }//GEN-LAST:event_UsernameInputActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpActionPerformed

    private void SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInActionPerformed
        
    }//GEN-LAST:event_SignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton SignIn;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
